name: 'Run Nox Session'
description: 'Action to run a nox session'
inputs:
  python_version:
    required: true
    type: string
    description: "python version to install for nox"
  nox_session:
    required: true
    type: string
    description: "name of the nox session to run"
outputs:
  nox_session_escape:
    description: "Escaped nox session"
    value: ${{ steps.escape-nox.outputs.nox_session_escape }}

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      # Do not run if no sessions (for example nox reuse_virtualenv)
      if:  ${{ inputs.python_version != '' }}
      with:
        python-version: |
          ${{ inputs.python_version }}
          3.9
        cache: "poetry"
    - uses: ./.github/workflows/actions/normalize_string
      id: escape-nox
      with:
        string_to_escape: ${{ inputs.nox_session }}
    - name: Cache .nox envdir
      uses: actions/cache@v3
      id: cache
      with:
        path: .nox
        key: nox-envdir-${{ runner.os }}-session-${{ steps.escape-nox.outputs.escaped }}
    - run: poetry run nox --session "${{ inputs.nox_session }}" --reuse-existing-virtualenvs
      shell: bash
